INPUT_DIR: input/input_syn_cfm_dim1
OUTPUT_BASE_DIR: output/output_syn_rec_cfm_dim1
DATA_KEYS:
- view_1
- view_2
- view_3
LIKELIHOOD_OPTIONS:
  view_1: gaussian
  view_2: gaussian
  view_3: gaussian
USE_COVARIATES: true
INIT_CFM: true
SYN_DATA_REC: true
FACTOR_INIT: PCA
N_ITERATIONS: 30
RESUME_TRAINING: true
SEEDS:
- 425946278
- 1738043719
- 299155385
- 1436947954
REF_SEED_DICT:
  5: 425946278
N_FACTORS_LIST:
- 5
- 5
- 5
- 5
