INPUT_DIR: input/input_gbm
OUTPUT_BASE_DIR: output/output_gbm_cfm_8
HDF5_INPUT: mefisto_model_untrained.hdf5
DATA_KEYS:
- gene_exp
- protein
LIKELIHOOD_OPTIONS:
  gene_exp: gaussian
  protein: gaussian
USE_COVARIATES: true
INIT_CFM: true
GRID_SCALING: 260
FACTOR_INIT: PCA
N_ITERATIONS: 30
RESUME_TRAINING: true
FLIP_IMAGE: true
PLOT_DOT_SIZE: 1
SEEDS:
- 117876074
- 1914660353
- 262588286
- 1435943220
REF_SEED_DICT:
  8: 117876074
N_FACTORS_LIST:
- 8
- 8
- 8
- 8
